import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: '1rem', background: '#eee' }}>
          <h1>My Blog</h1>
        </header>
        <main style={{ padding: '2rem' }}>{children}</main>
        <footer style={{ padding: '1rem', background: '#eee' }}>
          © 2025 My Blog
        </footer>
      </body>
    </html>
  )
}
